sudo: required
language: node_js
node_js:
- '10'

script:
- npm run lint
- npm run test
- npm run build

deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  local-dir: dist/
  repo: yhlben/front-end-navigation
  email: robot@travis.com
  name: robot
  github-token: $REPO_TOKEN
  keep-history: true
  on:
    branch: master
